blank_issues_enabled: false
contact_links:
  - name: "\U0001F4E7 Discussions(讨论)"
    url: https://github.com/AmazingAng/WTF-Solidity/discussions
    about: General discussions and request help from the community (与社区交流讨论和寻求帮助)
