name: 📚Typo report(勘误报告)
description: Report a typo in the WTF-Solidity (报告WTF-Solidity中的文字勘误)
labels:
  - documentation
title: "[Doc]"
body:
  - type: markdown
    attributes:
      value: |
        For better global communication, Please write in English.
        If you feel the description in English is not clear, then you can use Chinese, thanks!
        (为了更好的全球化的交流，请使用英文，如果觉得用英文无法清楚描述，可以使用中文，谢谢！）

  - type: textarea
    attributes:
      label: Details(细节)
      description: A short description what you find in our document.（简短的描述一下在文档中发现了什么错误。）

  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?(你愿意提交PR吗?)
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process especially if you already have a good understanding of how to implement the fix.
        (这不是必须的, 但是我们很高兴您能够提交PR)
      options:
        - label: Yes, I am willing to submit a PR!(是的, 我愿意提交PR)

  - type: markdown
    attributes:
      value: "Thanks for completing our form!(感谢填写表单！)"
