
name: Feature request（对此项目提出一个意见）
description: Suggest an idea for this project（对此项目提出一个意见）
title: "[Feature][Module Name（模块名称）] Feature title（标题）"
body:
  - type: markdown
    attributes:
      value: |
        能用英文用英文，觉得描述不清就用中文



  - type: textarea
    attributes:
      label:  Details(细节)
      description: Please describe your feature request in detail. (请详细描述您的功能请求。)

  - type: textarea
    attributes:
      label: Motivation(动机)
      description: Please describe your motivation in the feature request. (请描述您在功能请求中的动机。)
      placeholder: >
        Please describe your motivation in the feature request. (请描述您在功能请求中的动机。)



  - type: checkboxes
    attributes:
      label: Are you willing to submit a PR?(你愿意提交PR吗？)
      description: >
        This is absolutely not required, but we are happy to guide you in the contribution process
                especially if you already have a good understanding of how to implement the fix.
                （这不是必须的，但是我们很高兴您能够提交PR）
      options:
        - label: Yes I am willing to submit a PR!(是的我愿意)



  - type: markdown
    attributes:
      value: "Thanks for completing our form!"
